In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/saugataroyarghya/resume-dataset/resume_data.csv
/kaggle/input/datasets/kshitizregmi/jobs-and-job-description/job_title_des.csv
/kaggle/input/datasets/syedmharis/software-engineering-interview-questions-dataset/Software Questions.csv
/kaggle/input/datasets/darysha/hse-hackathon/train.csv
/kaggle/input/datasets/batuhanmutlu/job-skill-set/all_job_post.csv

In [2]:
import pandas as pd
import numpy as np

In [3]:
file_path = "/kaggle/input/datasets/darysha/hse-hackathon/train.csv"

with open(file_path, "r", encoding="utf-8") as f:
    for i in range(5):
        print(f.readline())

idCv|idVacancy|cv_status|locality|localityName|birthday|gender|age|positionName|dateCreate|typicalPosition_cv|dateModify_cv|publishedDate|academicDegree|skills_cv|driveLicenses|experience|otherCertificates|country|educationList|hardSkills_cv|softSkills_cv|workExperienceList|scheduleType_cv|salary_cv|retrainingCapability_cv|businessTrip|languageKnowledge_cv|relocation|innerInfo|salaryMin_cv|salaryMax_cv|education|id_vacancy|stateRegionCode_vacancy|vacancyName|codeProfession|codeProfessionalSphere|professionalSphereName|vacancyAddress|vacancyAddressHouse|vacancyAddressAdditionalInfo|geo|salary_vacancy|languageKnowledge_vacancy|busyType_vacancy|educationRequirements|hardSkills_vacancy|softSkills_vacancy|skills_vacancy|typicalPosition_vacancy|experienceRequirements|scheduleType_vacancy|otherVacancyBenefit|careerPerspective|idPriorityCategory|needMedcard|sourceType|requiredDriveLicense|retrainingCapability_vacancy|transportCompensation|changeTime|contactPerson|contactSource|company|fullCompanyName|oknpoCode|oksoCode|companyBusinessSize|dateModify_vacancy|workPlaces|federalDistrictCode|datePublished|isQuoted|creationDate|isMobilityProgram|isModerated|deleted|regionName|positionRequirements|contactList|additionalRequirements|salaryMin_vacancy|salaryMax_vacancy|qualifications|responsibilities|addressCode|addressOffice|medicalDocument|benefit|conditions

a4419ef0-93f4-11ec-a2fe-839f0d9a4379|72606f42-0c46-11ed-88f6-bf2cfe8c828d|Отказ|7000900100000.0|Томская-область,-Колпашевский-район,-г-Колпашево|1997-08-25T00:00:00+0400|Мужской|27.0|Музыкальный-руководитель|2022-02-22T18:32:27+0300||2023-01-10T08:48:09+0300|||[]|[]|2||"[{""countryName"": ""Российская Федерация"", ""countryCode"": ""RU""}]"|"[{""graduateYear"": 2015, ""instituteName"": ""ТСОШ"", ""type"": ""Education""}]"|[]|"[""Работа в команде"", ""Социальный интеллект""]"|"[{""companyName"": ""МКУ \""Городской молодёжный центр\"""", ""dateFrom"": ""2019-05-01T00:00:00+0300"", ""dateTo"": ""2021-08-01T00:00:00+0300"", ""demands"": ""Формирует их эстетический вкус, используя разные виды и формы организации музыкальной деятельности."", ""jobTitle"": ""Музыкальный руководитель"", ""relevant"": false, ""type"": ""WorkExperience"", ""militaryService"": false}, {""companyName"": ""Почта России"", ""dateFrom"": ""2022-09-01T00:00:00+0300"", ""dateTo"": ""2022-10-01T00:00:00+0300"", ""demands"": ""Доставка корреспонденции."", ""jobTitle"": ""Почтальон 2 класса"", ""relevant"": false, ""type"": ""WorkExperience"", ""militaryService"": false}, {""companyName"": ""СКБ Контур"", ""dateFrom"": ""2019-02-01T00:00:00+0300"", ""dateTo"": ""2019-03-01T00:00:00+0300"", ""demands"": ""Обзвон потенциальных покупателей и продажа услуг."", ""jobTitle"": ""Специалист по телемаркетингу"", ""relevant"": false, ""type"": ""WorkExperience"", ""militaryService"": false}]"|Полный-рабочий-день|30000.0|Готов-к-переобучению|Не-готов-к-командировкам|"[{""codeLanguage"": ""Английский"", ""level"": ""A1 — начальный"", ""type"": ""LanguageKnowledge""}, {""codeLanguage"": ""Русский"", ""level"": ""C2 — в совершенстве"", ""type"": ""LanguageKnowledge""}]"|Не-готов-к-переезду|"{""idUser"": ""c5e1dae0-03b1-11eb-8684-195c1cfba751"", ""rfCitizen"": ""Соискатель является гражданином РФ"", ""visibility"": ""Видно всем"", ""deleted"": false, ""dateModify"": ""2023-01-10T08:48:09+0300""}"|30000.0|30000.0|Среднее|72606f42-0c46-11ed-88f6-bf2cfe8c828d|7000000000000.0|Электромонтер по ремонту и обслуживанию электрооборудования|198616.0|Industry|Производство|Томская область||636462, г Колпашево, р-н Колпашевский, ул Обская, д. 67, корп. А|"{""latitude"": 58.32288, ""longitude"": 82.880904}"|от 40000|[]|Полная занятость|"{""educationType"": ""Среднее профессиональное""}"|[]|[]|[]||0.0|Сменная работа|Столовая Инфраструктурная доступность Социальный пакет В соответствии с трудовым договором. Применение рационального режима труда и отдыха, соблюдение санитарно-гигиенических норм, обеспечение охраны труда. Своевременная и в полном объеме выплата заработной платы в соответствии со своей квалификацией, сложностью труда, качеством выполняемой работы.|False||Не указано|Работодатель|[]|||2024-05-24T07:12:46+0300|Маленкова Наталья Викторовна|COMPANY|"{""companyCode"": ""1027003552564"", ""url"": ""https://trudvsem.ru/company/1027003552564"", ""inn"": ""7007000059"", ""email"": ""metallist_byh@mail.ru"", ""kpp"": ""700701001"", ""ogrn"": ""1027003552564""}"|"ЗАКРЫТОЕ АКЦИОНЕРНОЕ ОБЩЕСТВО ""МЕТАЛЛИСТ"""|||SMALL|2025-03-06T10:35:24+0300|1|6.0|2025-03-06 10:35:24+03:00|False|2022-07-25T21:20:22+0300|False|True|False|Томская область|Наличие опыта работы (желательно).|"[{""contactType"": ""Телефон"", ""contactValue"": ""3825441720"", ""isModerated"": true, ""isPreferred"": false}, {""contactType"": ""Эл. почта"", ""contactValue"": ""metallist_byh@mail.ru"", ""isModerated"": true, ""isPreferred"": false}, {""contactType"": ""Мобильный телефон"", ""isModerated"": true, ""isPreferred"": false}, {""contactType"": ""Скайп"", ""isModerated"": true, ""isPreferred"": false}, {""contactType"": ""Другое"", ""isModerated"": true, ""isPreferred"": false}]"|Ответственность|40000.0|50000.0|Наличие опыта работы (желательно).|Качественно и своевременно выполнять возложенные на него функции в соответствии с требованиями действующего законодательства, нормативных актов, положений, инструкций и приказов администрации. Выполнять ежедневные задания, полученные от ведущего инженера-энергетика и задания согласно утвержденному плану работы. Выполнять ремонт и обслуживание электрооборудования.|7000000000000.0||||

28438c80-77a8-11ed-bf5f-af80dfa0be97|0610f4d5-3667-11ee-a650-9586bb63c653|Отказ|5900000100000.0|Пермский-край,-г-Пермь|1986-10-19T15:00:00+0300|Женский|38.0|Специалист-по-кадровому-делопроизводству|2022-12-09T12:59:23+0300||2024-10-26T11:09:37+0300|2024-10-28 08:08:19+03:00||[]|[]|14||"[{""countryName"": ""Российская Федерация"", ""countryCode"": ""RU""}]"|"[{""faculty"": ""Документоведение и документационное обеспечение управления"", ""graduateYear"": 2012, ""instituteName"": ""ГОУ ВПО «Пермский государственный институт искусства и культуры»"", ""qualification"": ""Документовед"", ""speciality"": ""Документоведение и документационное обеспечение управления"", ""type"": ""Education""}, {""graduateYear"": 2008, ""instituteName"": ""ФГОУ СПО \""Пермский государственный автотранспортный колледж\"""", ""qualification"": ""Специалист по ДОУ, архивист, специалист по кадрам"", ""speciality"": ""Документационное обеспечение управления и архивоведение"", ""type"": ""Education""}]"|"[""делопроизводство"", ""кадровое делопроизводство"", ""навыки работы с интернетом и электронной почтой"", ""электронный документооборот"", ""деловая переписка""]"|"[""Умение обучать""]"|"[{""companyName"": ""ГБУЗ ПК \""Краевая стоматологическая поликлиника № 2\"" , Пермь"", ""dateFrom"": ""2015-06-15T00:00:00+0300"", ""dateTo"": ""2022-11-15T00:00:00+0300"", ""demands"": ""Обработка входящей и исходящей корреспонденции, ведение документооборота, прием и распределение входящих звонков, работа с посетителями, выполнение поручений руководителя, оформление организационно-распорядительной документации, информационно-справочных документов, служебных писем, оформление заявок для учебных центров. Работа в МСЭД, с электронной почтой, отправка писем по Почте России, оформление документов для подписки на периодические издания, выполнение кадровых функций на период отсутствия специалиста по кадрам."", ""jobTitle"": ""Секретарь-делопроизводитель"", ""relevant"": false, ""type"": ""WorkExperience"", ""militaryService"": false}, {""companyName"": ""МКУ «Пермская дирекция дорожного движения», Пермь"", ""dateFrom"": ""2014-11-15T00:00:00+0300"", ""dateTo"": ""2015-02-15T00:00:00+0300"", ""demands"": ""Прием, перевод, увольнение сотрудников, оформление приказов по основной деятельности, личному составу, оформление трудовых договоров, хранение и ведение трудовых книжек, работа в программе 1 С Зарплата и Управление персоналом 8.2 (Кадровый учет), работа с документами в системе электронного документооборота, ведение телефонных переговоров, прием посетителей."", ""jobTitle"": ""Секретарь руководителя – делопроизводитель 1-й категории"", ""relevant"": false, ""type"": ""WorkExperience"", ""militaryService"": false}, {""companyName"": ""ГБОУ СПО «Пермский педагогический колледж физической культуры и спорта» , Пермь"", ""dateFrom"": ""2013-04-15T01:00:00+0400"", ""dateTo"": ""2014-02-15T01:00:00+0400"", ""demands"": ""Прием, перевод, увольнение сотрудников, оформление приказов по отпускам, командировкам, оформление договоров, в т.ч. договоров ГПХ, составление справок о заработной плате, пособий, справок для назначения льготной пенсии, хранение и ведение трудовых книжек, заполнение листов нетрудоспособности, личных карточек (Т-2), составление и отправка отчетов по кадровому учету в вышестоящую организацию, территориальный орган федеральной службы государственной статистики по Пермскому краю, работа с входящей, исходящей корреспонденцией, работа в СЭД, прием и распределение входящих звонков."", ""jobTitle"": ""Специалист по кадрам, секретарь директора"", ""relevant"": false, ""type"": ""WorkExperience"", ""militaryService"": false}, {""companyName"": ""Министерство здравоохранения Пермского края, Пермь"", ""dateFrom"": ""2012-09-15T01:00:00+0400"", ""dateTo"": ""2012-11-15T01:00:00+0400"", ""demands"": ""Работа с входящей-исходящей корреспонденцией, формирование дел согласно номенклатуре, имеющейся у работодателя, отслеживание исполнительской дисциплины."", ""jobTitle"": ""Делопроизводитель"", ""relevant"": false, ""type"": ""WorkExperience"", ""militaryService"": false}, {""companyName"": ""ОАО НПО «Искра», Пермь"", ""dateFrom"": ""2008-07-15T00:00:00+0400"", ""dateTo"": ""2012-07-15T01:00:00+0400"", ""demands"": ""Ведение протоколов оперативных совещаний, оформление организационно-распорядительной документации; информационно-справочных документов; оформление служебной переписки как внешних, так и внутренних писем; регистрация документов и передача их на исполнение; контроль за исполнением документов; формирование дел в соответствии с утвержденной номенклатурой дел; проведение экспертизы ценности документов, организация телефонных переговоров, работа с посетителями; прием и передача телефонограмм, обеспечение отдела канцелярскими принадлежностями, выполнение поручений руководителя."", ""jobTitle"": ""Секретарь"", ""relevant"": false, ""type"": ""WorkExperience"", ""militaryService"": false}, {""companyName"": ""ООО \""ГрадиентМ\"""", ""dateFrom"": ""2023-03-15T00:00:00+0300"", ""dateTo"": ""2023-07-15T00:00:00+0300"", ""demands"": ""Прием, перевод, увольнение сотрудников, оформление табелей учета рабочего времени, оформление трудовых договоров, отпусков сотрудников, хранение и ведение трудовых книжек, сдача кадровой отчетности в Социальный фонд России, работа в программе 1 С Зарплата и Управление персоналом (Кадровый учет). Размещение вакансий на сайтах, приглашение соискателей на собеседование."", ""jobTitle"": ""Специалист по кадрам"", ""relevant"": false, ""type"": ""WorkExperience"", ""militaryService"": false}, {""companyName"": ""ФГБОУ ВО \""Российская академия народного хозяйства и государственной службы при Президенте Российской Федерации\"""", ""dateFrom"": ""2023-10-15T00:00:00+0300"", ""dateTo"": ""2024-07-15T00:00:00+0300"", ""demands"": ""Оформление и распечатка дипломов и приложений к дипломам о высшем образовании. Работа в 1 С:КАС, с электронной почтой академии. Оформление дубликатов дипломов о высшем образовании и дубликатов приложений к ним. Оформление академических справок о периоде обучения. Работа с бланками строгой отчетности. Ведение ведомостей выданных дипломов о высшем образовании и приложений к ним, книги учета выдачи документов о высшем образовании, книги выдачи справок о периоде обучение, книги выдачи государственных справок о периоде обучения в образовательной организации, книги выдачи дубликатов документов о высшем образовании. Оформление и сдача отчетности по Федеральному реестру сведений документов об образовании. Оформление квартального отчета и сдача его в бухгалтерию о списанных и испорченных бланках строгой отчетности."", ""jobTitle"": ""Специалист учебно-методического отдела"", ""relevant"": false, ""type"": ""WorkExperience"", ""militaryService"": false}]"|Полный-рабочий-день|35000.0|Готов-к-переобучению|Не-готов-к-командировкам|"[{""codeLanguage"": ""Русский"", ""level"": ""A1 — начальный"", ""type"": ""LanguageKnowledge""}]"|Не-готов-к-переезду|"{""rfCitizen"": ""Соискатель является гражданином РФ"", ""visibility"": ""Видно всем"", ""deleted"": false, ""dateModify"": ""2024-10-26T11:09:37+0300""}"|35000.0|35000.0|Высшее-бакалавриат|0610f4d5-3667-11ee-a650-9586bb63c653|5900000000000.0|Специалист по кадрам|265833.0|HumanRecruitment|Кадровая служба, управление персоналом|Пермский край, Город Пермь, Окулова улица, 27|27|Окулова, 27 этаж 5 кабинет 503, (вход справа под навесом) |"{""latitude"": 58.013726, ""longitude"": 56.217478}"|от 36122|[]|Полная занятость|"{""educationType"": ""Среднее профессиональное""}"|[]|[]|[]||1.0|Полный рабочий день|Стабильность, регулярная индексация заработной платы, карьерный рост, обучение. Рассмотрим кандидатов без опыта работы при наличии соответствующей профессиональной подготовки. Пятница сокращенный рабочий день до 16.30|True||Не требуется|Работодатель|[]|||2025-02-24T06:53:30+0300|Светлана Яковлевна||"{""companyCode"": ""1195958013536"", ""url"": ""https://trudvsem.ru/company/1195958013536"", ""inn"": ""5902053345"", ""email"": ""info@cbu-perm.ru"", ""kpp"": ""590401001"", ""ogrn"": ""1195958013536""}"|"ГОСУДАРСТВЕННОЕ КАЗЕННОЕ УЧРЕЖДЕНИЕ ПЕРМСКОГО КРАЯ ""ЦЕНТР БУХГАЛТЕРСКОГО УЧЕТА"""|||SMALL|2025-03-24T08:50:57+0300|3|4.0|2025-03-24 08:50:57+03:00|False|2023-08-09T06:44:20+0300|False|True|False|Пермский край|среднее или высшее профессиональное образование специалитет, магистратура, дополнительное профессиональное образование - программы повышения квалификации в области управления персоналом; программы профессиональной переподготовки в области управления персоналом. опыт работы в области управления персоналом, кадровом делопроизводстве знание системы 1С 8.3 предпочителен опыт работы в государственной системе здравоохранения со знанием системы ЕДИНОЙ ИНФОРМАЦИОННОЙ СИСТЕМЫ УПРАВЛЕНИЯ ФИНАНСОВО-ХОЗЯЙСТВЕННОЙ ДЕЯТЕЛЬНОСТЬЮ ОРГАНИЗАЦИЙ ГОСУДАРСТВЕННОГО СЕКТОРА ПЕРМСКОГО КРАЯ - ЕИС УФХД ПК|"[{""contactType"": ""Телефон"", ""contactValue"": ""3422061994"", ""isModerated"": true, ""isPreferred"": false}, {""contactType"": ""Мобильный телефон"", ""contactValue"": ""9523326488"", ""isModerated"": true, ""isPreferred"": false}, {""contactType"": ""Эл. почта"", ""contactValue"": ""semenova.sya@cbu-perm.ru"", ""isModerated"": true, ""isPreferred"": false}, {""contactType"": ""Скайп"", ""isModerated"": true, ""isPreferred"": false}, {""contactType"": ""Другое"", ""isModerated"": true, ""isPreferred"": false}]"|"Работа в организации ""Центр бухгалтерского учета"", оказывающей услуги по бухгалтерскому и кадровому учету учреждениям здравоохранения Пермского края. Желателен опыт работы в бюжетной сфере, в системе здравоохранения."|36122.0|45000.0|среднее или высшее профессиональное образование специалитет, магистратура, дополнительное профессиональное образование - программы повышения квалификации в области управления персоналом; программы профессиональной переподготовки в области управления персоналом. опыт работы в области управления персоналом, кадровом делопроизводстве знание системы 1С 8.3 предпочителен опыт работы в государственной системе здравоохранения со знанием системы ЕДИНОЙ ИНФОРМАЦИОННОЙ СИСТЕМЫ УПРАВЛЕНИЯ ФИНАНСОВО-ХОЗЯЙСТВЕННОЙ ДЕЯТЕЛЬНОСТЬЮ ОРГАНИЗАЦИЙ ГОСУДАРСТВЕННОГО СЕКТОРА ПЕРМСКОГО КРАЯ - ЕИС УФХД ПК|Подготовка кадровых документов (приемы, переводы, увольнения, отпуска, доплаты, оформление приказов по обучению сотрудников), подготовка и сдача отчетных форм|5.90000010000853e+16||||Оптимальные


In [4]:
# Resume Dataset
resume_df = pd.read_csv("/kaggle/input/datasets/saugataroyarghya/resume-dataset/resume_data.csv")

# Resume-Job Matching Dataset
matching_df = pd.read_csv(
    "/kaggle/input/datasets/darysha/hse-hackathon/train.csv",
    sep="|"
)
# Job Title and Job Description Dataset
jobs_df = pd.read_csv("/kaggle/input/datasets/kshitizregmi/jobs-and-job-description/job_title_des.csv")

# Job Skill Set Dataset
skills_df = pd.read_csv("/kaggle/input/datasets/batuhanmutlu/job-skill-set/all_job_post.csv")

# Software Engineering Interview Questions Dataset
interview_df = pd.read_csv(
    "/kaggle/input/datasets/syedmharis/software-engineering-interview-questions-dataset/Software Questions.csv",
    encoding="cp1252"
)

In [5]:
interview_df.head()

,Question Number,Question,Answer,Category,Difficulty
0,1,What is the difference between compilation and...,Compilation translates source code into machin...,General Programming,Medium
1,2,Explain the concept of polymorphism.,Polymorphism allows objects of different class...,General Programming,Medium
2,3,Define encapsulation and give an example.,Encapsulation bundles data and methods in a cl...,General Programming,Hard
3,4,"What is an abstract class, and how is it diffe...",An abstract class can't be instantiated and ca...,General Programming,Medium
4,5,Describe the principles of Object-Oriented Pro...,"OOP principles include encapsulation, inherita...",General Programming,Medium

In [6]:
import os

path = "/kaggle/input/datasets/darysha/hse-hackathon"

print(os.listdir(path))

['train.csv']

In [7]:
file_path = "/kaggle/input/datasets/darysha/hse-hackathon/train.csv"

with open(file_path, "r", encoding="utf-8") as f:
    for i in range(5):
        print(f.readline())

idCv|idVacancy|cv_status|locality|localityName|birthday|gender|age|positionName|dateCreate|typicalPosition_cv|dateModify_cv|publishedDate|academicDegree|skills_cv|driveLicenses|experience|otherCertificates|country|educationList|hardSkills_cv|softSkills_cv|workExperienceList|scheduleType_cv|salary_cv|retrainingCapability_cv|businessTrip|languageKnowledge_cv|relocation|innerInfo|salaryMin_cv|salaryMax_cv|education|id_vacancy|stateRegionCode_vacancy|vacancyName|codeProfession|codeProfessionalSphere|professionalSphereName|vacancyAddress|vacancyAddressHouse|vacancyAddressAdditionalInfo|geo|salary_vacancy|languageKnowledge_vacancy|busyType_vacancy|educationRequirements|hardSkills_vacancy|softSkills_vacancy|skills_vacancy|typicalPosition_vacancy|experienceRequirements|scheduleType_vacancy|otherVacancyBenefit|careerPerspective|idPriorityCategory|needMedcard|sourceType|requiredDriveLicense|retrainingCapability_vacancy|transportCompensation|changeTime|contactPerson|contactSource|company|fullCompanyName|oknpoCode|oksoCode|companyBusinessSize|dateModify_vacancy|workPlaces|federalDistrictCode|datePublished|isQuoted|creationDate|isMobilityProgram|isModerated|deleted|regionName|positionRequirements|contactList|additionalRequirements|salaryMin_vacancy|salaryMax_vacancy|qualifications|responsibilities|addressCode|addressOffice|medicalDocument|benefit|conditions

a4419ef0-93f4-11ec-a2fe-839f0d9a4379|72606f42-0c46-11ed-88f6-bf2cfe8c828d|Отказ|7000900100000.0|Томская-область,-Колпашевский-район,-г-Колпашево|1997-08-25T00:00:00+0400|Мужской|27.0|Музыкальный-руководитель|2022-02-22T18:32:27+0300||2023-01-10T08:48:09+0300|||[]|[]|2||"[{""countryName"": ""Российская Федерация"", ""countryCode"": ""RU""}]"|"[{""graduateYear"": 2015, ""instituteName"": ""ТСОШ"", ""type"": ""Education""}]"|[]|"[""Работа в команде"", ""Социальный интеллект""]"|"[{""companyName"": ""МКУ \""Городской молодёжный центр\"""", ""dateFrom"": ""2019-05-01T00:00:00+0300"", ""dateTo"": ""2021-08-01T00:00:00+0300"", ""demands"": ""Формирует их эстетический вкус, используя разные виды и формы организации музыкальной деятельности."", ""jobTitle"": ""Музыкальный руководитель"", ""relevant"": false, ""type"": ""WorkExperience"", ""militaryService"": false}, {""companyName"": ""Почта России"", ""dateFrom"": ""2022-09-01T00:00:00+0300"", ""dateTo"": ""2022-10-01T00:00:00+0300"", ""demands"": ""Доставка корреспонденции."", ""jobTitle"": ""Почтальон 2 класса"", ""relevant"": false, ""type"": ""WorkExperience"", ""militaryService"": false}, {""companyName"": ""СКБ Контур"", ""dateFrom"": ""2019-02-01T00:00:00+0300"", ""dateTo"": ""2019-03-01T00:00:00+0300"", ""demands"": ""Обзвон потенциальных покупателей и продажа услуг."", ""jobTitle"": ""Специалист по телемаркетингу"", ""relevant"": false, ""type"": ""WorkExperience"", ""militaryService"": false}]"|Полный-рабочий-день|30000.0|Готов-к-переобучению|Не-готов-к-командировкам|"[{""codeLanguage"": ""Английский"", ""level"": ""A1 — начальный"", ""type"": ""LanguageKnowledge""}, {""codeLanguage"": ""Русский"", ""level"": ""C2 — в совершенстве"", ""type"": ""LanguageKnowledge""}]"|Не-готов-к-переезду|"{""idUser"": ""c5e1dae0-03b1-11eb-8684-195c1cfba751"", ""rfCitizen"": ""Соискатель является гражданином РФ"", ""visibility"": ""Видно всем"", ""deleted"": false, ""dateModify"": ""2023-01-10T08:48:09+0300""}"|30000.0|30000.0|Среднее|72606f42-0c46-11ed-88f6-bf2cfe8c828d|7000000000000.0|Электромонтер по ремонту и обслуживанию электрооборудования|198616.0|Industry|Производство|Томская область||636462, г Колпашево, р-н Колпашевский, ул Обская, д. 67, корп. А|"{""latitude"": 58.32288, ""longitude"": 82.880904}"|от 40000|[]|Полная занятость|"{""educationType"": ""Среднее профессиональное""}"|[]|[]|[]||0.0|Сменная работа|Столовая Инфраструктурная доступность Социальный пакет В соответствии с трудовым договором. Применение рационального режима труда и отдыха, соблюдение санитарно-гигиенических норм, обеспечение охраны труда. Своевременная и в полном объеме выплата заработной платы в соответствии со своей квалификацией, сложностью труда, качеством выполняемой работы.|False||Не указано|Работодатель|[]|||2024-05-24T07:12:46+0300|Маленкова Наталья Викторовна|COMPANY|"{""companyCode"": ""1027003552564"", ""url"": ""https://trudvsem.ru/company/1027003552564"", ""inn"": ""7007000059"", ""email"": ""metallist_byh@mail.ru"", ""kpp"": ""700701001"", ""ogrn"": ""1027003552564""}"|"ЗАКРЫТОЕ АКЦИОНЕРНОЕ ОБЩЕСТВО ""МЕТАЛЛИСТ"""|||SMALL|2025-03-06T10:35:24+0300|1|6.0|2025-03-06 10:35:24+03:00|False|2022-07-25T21:20:22+0300|False|True|False|Томская область|Наличие опыта работы (желательно).|"[{""contactType"": ""Телефон"", ""contactValue"": ""3825441720"", ""isModerated"": true, ""isPreferred"": false}, {""contactType"": ""Эл. почта"", ""contactValue"": ""metallist_byh@mail.ru"", ""isModerated"": true, ""isPreferred"": false}, {""contactType"": ""Мобильный телефон"", ""isModerated"": true, ""isPreferred"": false}, {""contactType"": ""Скайп"", ""isModerated"": true, ""isPreferred"": false}, {""contactType"": ""Другое"", ""isModerated"": true, ""isPreferred"": false}]"|Ответственность|40000.0|50000.0|Наличие опыта работы (желательно).|Качественно и своевременно выполнять возложенные на него функции в соответствии с требованиями действующего законодательства, нормативных актов, положений, инструкций и приказов администрации. Выполнять ежедневные задания, полученные от ведущего инженера-энергетика и задания согласно утвержденному плану работы. Выполнять ремонт и обслуживание электрооборудования.|7000000000000.0||||

28438c80-77a8-11ed-bf5f-af80dfa0be97|0610f4d5-3667-11ee-a650-9586bb63c653|Отказ|5900000100000.0|Пермский-край,-г-Пермь|1986-10-19T15:00:00+0300|Женский|38.0|Специалист-по-кадровому-делопроизводству|2022-12-09T12:59:23+0300||2024-10-26T11:09:37+0300|2024-10-28 08:08:19+03:00||[]|[]|14||"[{""countryName"": ""Российская Федерация"", ""countryCode"": ""RU""}]"|"[{""faculty"": ""Документоведение и документационное обеспечение управления"", ""graduateYear"": 2012, ""instituteName"": ""ГОУ ВПО «Пермский государственный институт искусства и культуры»"", ""qualification"": ""Документовед"", ""speciality"": ""Документоведение и документационное обеспечение управления"", ""type"": ""Education""}, {""graduateYear"": 2008, ""instituteName"": ""ФГОУ СПО \""Пермский государственный автотранспортный колледж\"""", ""qualification"": ""Специалист по ДОУ, архивист, специалист по кадрам"", ""speciality"": ""Документационное обеспечение управления и архивоведение"", ""type"": ""Education""}]"|"[""делопроизводство"", ""кадровое делопроизводство"", ""навыки работы с интернетом и электронной почтой"", ""электронный документооборот"", ""деловая переписка""]"|"[""Умение обучать""]"|"[{""companyName"": ""ГБУЗ ПК \""Краевая стоматологическая поликлиника № 2\"" , Пермь"", ""dateFrom"": ""2015-06-15T00:00:00+0300"", ""dateTo"": ""2022-11-15T00:00:00+0300"", ""demands"": ""Обработка входящей и исходящей корреспонденции, ведение документооборота, прием и распределение входящих звонков, работа с посетителями, выполнение поручений руководителя, оформление организационно-распорядительной документации, информационно-справочных документов, служебных писем, оформление заявок для учебных центров. Работа в МСЭД, с электронной почтой, отправка писем по Почте России, оформление документов для подписки на периодические издания, выполнение кадровых функций на период отсутствия специалиста по кадрам."", ""jobTitle"": ""Секретарь-делопроизводитель"", ""relevant"": false, ""type"": ""WorkExperience"", ""militaryService"": false}, {""companyName"": ""МКУ «Пермская дирекция дорожного движения», Пермь"", ""dateFrom"": ""2014-11-15T00:00:00+0300"", ""dateTo"": ""2015-02-15T00:00:00+0300"", ""demands"": ""Прием, перевод, увольнение сотрудников, оформление приказов по основной деятельности, личному составу, оформление трудовых договоров, хранение и ведение трудовых книжек, работа в программе 1 С Зарплата и Управление персоналом 8.2 (Кадровый учет), работа с документами в системе электронного документооборота, ведение телефонных переговоров, прием посетителей."", ""jobTitle"": ""Секретарь руководителя – делопроизводитель 1-й категории"", ""relevant"": false, ""type"": ""WorkExperience"", ""militaryService"": false}, {""companyName"": ""ГБОУ СПО «Пермский педагогический колледж физической культуры и спорта» , Пермь"", ""dateFrom"": ""2013-04-15T01:00:00+0400"", ""dateTo"": ""2014-02-15T01:00:00+0400"", ""demands"": ""Прием, перевод, увольнение сотрудников, оформление приказов по отпускам, командировкам, оформление договоров, в т.ч. договоров ГПХ, составление справок о заработной плате, пособий, справок для назначения льготной пенсии, хранение и ведение трудовых книжек, заполнение листов нетрудоспособности, личных карточек (Т-2), составление и отправка отчетов по кадровому учету в вышестоящую организацию, территориальный орган федеральной службы государственной статистики по Пермскому краю, работа с входящей, исходящей корреспонденцией, работа в СЭД, прием и распределение входящих звонков."", ""jobTitle"": ""Специалист по кадрам, секретарь директора"", ""relevant"": false, ""type"": ""WorkExperience"", ""militaryService"": false}, {""companyName"": ""Министерство здравоохранения Пермского края, Пермь"", ""dateFrom"": ""2012-09-15T01:00:00+0400"", ""dateTo"": ""2012-11-15T01:00:00+0400"", ""demands"": ""Работа с входящей-исходящей корреспонденцией, формирование дел согласно номенклатуре, имеющейся у работодателя, отслеживание исполнительской дисциплины."", ""jobTitle"": ""Делопроизводитель"", ""relevant"": false, ""type"": ""WorkExperience"", ""militaryService"": false}, {""companyName"": ""ОАО НПО «Искра», Пермь"", ""dateFrom"": ""2008-07-15T00:00:00+0400"", ""dateTo"": ""2012-07-15T01:00:00+0400"", ""demands"": ""Ведение протоколов оперативных совещаний, оформление организационно-распорядительной документации; информационно-справочных документов; оформление служебной переписки как внешних, так и внутренних писем; регистрация документов и передача их на исполнение; контроль за исполнением документов; формирование дел в соответствии с утвержденной номенклатурой дел; проведение экспертизы ценности документов, организация телефонных переговоров, работа с посетителями; прием и передача телефонограмм, обеспечение отдела канцелярскими принадлежностями, выполнение поручений руководителя."", ""jobTitle"": ""Секретарь"", ""relevant"": false, ""type"": ""WorkExperience"", ""militaryService"": false}, {""companyName"": ""ООО \""ГрадиентМ\"""", ""dateFrom"": ""2023-03-15T00:00:00+0300"", ""dateTo"": ""2023-07-15T00:00:00+0300"", ""demands"": ""Прием, перевод, увольнение сотрудников, оформление табелей учета рабочего времени, оформление трудовых договоров, отпусков сотрудников, хранение и ведение трудовых книжек, сдача кадровой отчетности в Социальный фонд России, работа в программе 1 С Зарплата и Управление персоналом (Кадровый учет). Размещение вакансий на сайтах, приглашение соискателей на собеседование."", ""jobTitle"": ""Специалист по кадрам"", ""relevant"": false, ""type"": ""WorkExperience"", ""militaryService"": false}, {""companyName"": ""ФГБОУ ВО \""Российская академия народного хозяйства и государственной службы при Президенте Российской Федерации\"""", ""dateFrom"": ""2023-10-15T00:00:00+0300"", ""dateTo"": ""2024-07-15T00:00:00+0300"", ""demands"": ""Оформление и распечатка дипломов и приложений к дипломам о высшем образовании. Работа в 1 С:КАС, с электронной почтой академии. Оформление дубликатов дипломов о высшем образовании и дубликатов приложений к ним. Оформление академических справок о периоде обучения. Работа с бланками строгой отчетности. Ведение ведомостей выданных дипломов о высшем образовании и приложений к ним, книги учета выдачи документов о высшем образовании, книги выдачи справок о периоде обучение, книги выдачи государственных справок о периоде обучения в образовательной организации, книги выдачи дубликатов документов о высшем образовании. Оформление и сдача отчетности по Федеральному реестру сведений документов об образовании. Оформление квартального отчета и сдача его в бухгалтерию о списанных и испорченных бланках строгой отчетности."", ""jobTitle"": ""Специалист учебно-методического отдела"", ""relevant"": false, ""type"": ""WorkExperience"", ""militaryService"": false}]"|Полный-рабочий-день|35000.0|Готов-к-переобучению|Не-готов-к-командировкам|"[{""codeLanguage"": ""Русский"", ""level"": ""A1 — начальный"", ""type"": ""LanguageKnowledge""}]"|Не-готов-к-переезду|"{""rfCitizen"": ""Соискатель является гражданином РФ"", ""visibility"": ""Видно всем"", ""deleted"": false, ""dateModify"": ""2024-10-26T11:09:37+0300""}"|35000.0|35000.0|Высшее-бакалавриат|0610f4d5-3667-11ee-a650-9586bb63c653|5900000000000.0|Специалист по кадрам|265833.0|HumanRecruitment|Кадровая служба, управление персоналом|Пермский край, Город Пермь, Окулова улица, 27|27|Окулова, 27 этаж 5 кабинет 503, (вход справа под навесом) |"{""latitude"": 58.013726, ""longitude"": 56.217478}"|от 36122|[]|Полная занятость|"{""educationType"": ""Среднее профессиональное""}"|[]|[]|[]||1.0|Полный рабочий день|Стабильность, регулярная индексация заработной платы, карьерный рост, обучение. Рассмотрим кандидатов без опыта работы при наличии соответствующей профессиональной подготовки. Пятница сокращенный рабочий день до 16.30|True||Не требуется|Работодатель|[]|||2025-02-24T06:53:30+0300|Светлана Яковлевна||"{""companyCode"": ""1195958013536"", ""url"": ""https://trudvsem.ru/company/1195958013536"", ""inn"": ""5902053345"", ""email"": ""info@cbu-perm.ru"", ""kpp"": ""590401001"", ""ogrn"": ""1195958013536""}"|"ГОСУДАРСТВЕННОЕ КАЗЕННОЕ УЧРЕЖДЕНИЕ ПЕРМСКОГО КРАЯ ""ЦЕНТР БУХГАЛТЕРСКОГО УЧЕТА"""|||SMALL|2025-03-24T08:50:57+0300|3|4.0|2025-03-24 08:50:57+03:00|False|2023-08-09T06:44:20+0300|False|True|False|Пермский край|среднее или высшее профессиональное образование специалитет, магистратура, дополнительное профессиональное образование - программы повышения квалификации в области управления персоналом; программы профессиональной переподготовки в области управления персоналом. опыт работы в области управления персоналом, кадровом делопроизводстве знание системы 1С 8.3 предпочителен опыт работы в государственной системе здравоохранения со знанием системы ЕДИНОЙ ИНФОРМАЦИОННОЙ СИСТЕМЫ УПРАВЛЕНИЯ ФИНАНСОВО-ХОЗЯЙСТВЕННОЙ ДЕЯТЕЛЬНОСТЬЮ ОРГАНИЗАЦИЙ ГОСУДАРСТВЕННОГО СЕКТОРА ПЕРМСКОГО КРАЯ - ЕИС УФХД ПК|"[{""contactType"": ""Телефон"", ""contactValue"": ""3422061994"", ""isModerated"": true, ""isPreferred"": false}, {""contactType"": ""Мобильный телефон"", ""contactValue"": ""9523326488"", ""isModerated"": true, ""isPreferred"": false}, {""contactType"": ""Эл. почта"", ""contactValue"": ""semenova.sya@cbu-perm.ru"", ""isModerated"": true, ""isPreferred"": false}, {""contactType"": ""Скайп"", ""isModerated"": true, ""isPreferred"": false}, {""contactType"": ""Другое"", ""isModerated"": true, ""isPreferred"": false}]"|"Работа в организации ""Центр бухгалтерского учета"", оказывающей услуги по бухгалтерскому и кадровому учету учреждениям здравоохранения Пермского края. Желателен опыт работы в бюжетной сфере, в системе здравоохранения."|36122.0|45000.0|среднее или высшее профессиональное образование специалитет, магистратура, дополнительное профессиональное образование - программы повышения квалификации в области управления персоналом; программы профессиональной переподготовки в области управления персоналом. опыт работы в области управления персоналом, кадровом делопроизводстве знание системы 1С 8.3 предпочителен опыт работы в государственной системе здравоохранения со знанием системы ЕДИНОЙ ИНФОРМАЦИОННОЙ СИСТЕМЫ УПРАВЛЕНИЯ ФИНАНСОВО-ХОЗЯЙСТВЕННОЙ ДЕЯТЕЛЬНОСТЬЮ ОРГАНИЗАЦИЙ ГОСУДАРСТВЕННОГО СЕКТОРА ПЕРМСКОГО КРАЯ - ЕИС УФХД ПК|Подготовка кадровых документов (приемы, переводы, увольнения, отпуска, доплаты, оформление приказов по обучению сотрудников), подготовка и сдача отчетных форм|5.90000010000853e+16||||Оптимальные


In [8]:
import pandas as pd

# Job Title and Description Dataset
jobs_df = pd.read_csv("/kaggle/input/datasets/kshitizregmi/jobs-and-job-description/job_title_des.csv")

# Job Skills Dataset
skills_df = pd.read_csv("/kaggle/input/datasets/batuhanmutlu/job-skill-set/all_job_post.csv")

# Resume Dataset
resume_df = pd.read_csv("/kaggle/input/datasets/saugataroyarghya/resume-dataset/resume_data.csv")

In [9]:
datasets = {
    "Jobs": jobs_df,
    "Skills": skills_df,
    "Resume": resume_df
}

for name, df in datasets.items():
    print("=" * 60)
    print(f"Dataset: {name}")
    print("=" * 60)

    print("\nShape:")
    print(df.shape)

    print("\nColumns:")
    print(df.columns.tolist())

    print("\nMissing Values:")
    print(df.isnull().sum())

    print("\nFirst 3 Rows:")
    display(df.head(3))

    print("\n\n")

============================================================
Dataset: Jobs
============================================================

Shape:
(2277, 3)

Columns:
['Unnamed: 0', 'Job Title', 'Job Description']

Missing Values:
Unnamed: 0         0
Job Title          0
Job Description    0
dtype: int64

First 3 Rows:

,Unnamed: 0,Job Title,Job Description
0,0,Flutter Developer,We are looking for hire experts flutter develo...
1,1,Django Developer,PYTHON/DJANGO (Developer/Lead) - Job Code(PDJ ...
2,2,Machine Learning,"Data Scientist (Contractor)\n\nBangalore, IN\n..."

============================================================
Dataset: Skills
============================================================

Shape:
(1167, 5)

Columns:
['job_id', 'category', 'job_title', 'job_description', 'job_skill_set']

Missing Values:
job_id             0
category           0
job_title          0
job_description    0
job_skill_set      0
dtype: int64

First 3 Rows:

,job_id,category,job_title,job_description,job_skill_set
0,3902668440,HR,Sr Human Resource Generalist,SUMMARY\nTHE SR. HR GENERALIST PROVIDES HR EXP...,"['employee relations', 'talent acquisition', '..."
1,3905823748,HR,Human Resources Manager,BE PART OF A STELLAR TEAM AT YSB AS THE MANAGE...,"['Talent Acquisition', 'Employee Performance M..."
2,3905854799,HR,Director of Human Resources,OUR CLIENT IS A THRIVING ORGANIZATION OFFERING...,"['Human Resources Management', 'Recruitment', ..."

============================================================
Dataset: Resume
============================================================

Shape:
(9544, 35)

Columns:
['address', 'career_objective', 'skills', 'educational_institution_name', 'degree_names', 'passing_years', 'educational_results', 'result_types', 'major_field_of_studies', 'professional_company_names', 'company_urls', 'start_dates', 'end_dates', 'related_skils_in_job', 'positions', 'locations', 'responsibilities', 'extra_curricular_activity_types', 'extra_curricular_organization_names', 'extra_curricular_organization_links', 'role_positions', 'languages', 'proficiency_levels', 'certification_providers', 'certification_skills', 'online_links', 'issue_dates', 'expiry_dates', '\ufeffjob_position_name', 'educationaL_requirements', 'experiencere_requirement', 'age_requirement', 'responsibilities.1', 'skills_required', 'matched_score']

Missing Values:
address                                8760
career_objective                       4804
skills                                   56
educational_institution_name             84
degree_names                             84
passing_years                            84
educational_results                      84
result_types                             84
major_field_of_studies                   84
professional_company_names               84
company_urls                             84
start_dates                              84
end_dates                                84
related_skils_in_job                     84
positions                                84
locations                                84
responsibilities                          0
extra_curricular_activity_types        6118
extra_curricular_organization_names    6118
extra_curricular_organization_links    6118
role_positions                         6118
languages                              8844
proficiency_levels                     8844
certification_providers                7536
certification_skills                   7536
online_links                           7536
issue_dates                            7536
expiry_dates                           7536
﻿job_position_name                        0
educationaL_requirements                  0
experiencere_requirement               1364
age_requirement                        4087
responsibilities.1                        0
skills_required                        1701
matched_score                             0
dtype: int64

First 3 Rows:

,address,career_objective,skills,educational_institution_name,degree_names,passing_years,educational_results,result_types,major_field_of_studies,professional_company_names,...,online_links,issue_dates,expiry_dates,﻿job_position_name,educationaL_requirements,experiencere_requirement,age_requirement,responsibilities.1,skills_required,matched_score
0,NaN,Big data analytics working and database wareho...,"['Big Data', 'Hadoop', 'Hive', 'Python', 'Mapr...",['The Amity School of Engineering & Technology...,['B.Tech'],['2019'],['N/A'],[None],['Electronics'],['Coca-COla'],...,NaN,NaN,NaN,Senior Software Engineer,B.Sc in Computer Science & Engineering from a ...,At least 1 year,NaN,Technical Support\nTroubleshooting\nCollaborat...,NaN,0.850000
1,NaN,Fresher looking to join as a data analyst and ...,"['Data Analysis', 'Data Analytics', 'Business ...","['Delhi University - Hansraj College', 'Delhi ...","['B.Sc (Maths)', 'M.Sc (Science) (Statistics)']","['2015', '2018']","['N/A', 'N/A']","['N/A', 'N/A']","['Mathematics', 'Statistics']",['BIB Consultancy'],...,NaN,NaN,NaN,Machine Learning (ML) Engineer,M.Sc in Computer Science & Engineering or in a...,At least 5 year(s),NaN,Machine Learning Leadership\nCross-Functional ...,NaN,0.750000
2,NaN,NaN,"['Software Development', 'Machine Learning', '...","['Birla Institute of Technology (BIT), Ranchi']",['B.Tech'],['2018'],['N/A'],['N/A'],['Electronics/Telecommunication'],['Axis Bank Limited'],...,NaN,NaN,NaN,"Executive/ Senior Executive- Trade Marketing, ...",Master of Business Administration (MBA),At least 3 years,NaN,"Trade Marketing Executive\nBrand Visibility, S...",Brand Promotion\nCampaign Management\nField Su...,0.416667

In [10]:
print(resume_df.info())
display(resume_df.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9544 entries, 0 to 9543
Data columns (total 35 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   address                              784 non-null    object
 1   career_objective                     4740 non-null   object
 2   skills                               9488 non-null   object
 3   educational_institution_name         9460 non-null   object
 4   degree_names                         9460 non-null   object
 5   passing_years                        9460 non-null   object
 6   educational_results                  9460 non-null   object
 7   result_types                         9460 non-null   object
 8   major_field_of_studies               9460 non-null   object
 9   professional_company_names           9460 non-null   object
 10  company_urls                         9460 non-null   object
 11  start_dates                          9460 non-null   object
 12  end_dates                            9460 non-null   object
 13  related_skils_in_job                 9460 non-null   object
 14  positions                            9460 non-null   object
 15  locations                            9460 non-null   object
 16  responsibilities                     9544 non-null   object
 17  extra_curricular_activity_types      3426 non-null   object
 18  extra_curricular_organization_names  3426 non-null   object
 19  extra_curricular_organization_links  3426 non-null   object
 20  role_positions                       3426 non-null   object
 21  languages                            700 non-null    object
 22  proficiency_levels                   700 non-null    object
 23  certification_providers              2008 non-null   object
 24  certification_skills                 2008 non-null   object
 25  online_links                         2008 non-null   object
 26  issue_dates                          2008 non-null   object
 27  expiry_dates                         2008 non-null   object
 28  ﻿job_position_name                   9544 non-null   object
 29  educationaL_requirements             9544 non-null   object
 30  experiencere_requirement             8180 non-null   object
 31  age_requirement                      5457 non-null   object
 32  responsibilities.1                   9544 non-null   object
 33  skills_required                      7843 non-null   object
 34  matched_score                        9544 non-null   float64
dtypes: float64(1), object(34)
memory usage: 2.5+ MB
None

,address,career_objective,skills,educational_institution_name,degree_names,passing_years,educational_results,result_types,major_field_of_studies,professional_company_names,...,online_links,issue_dates,expiry_dates,﻿job_position_name,educationaL_requirements,experiencere_requirement,age_requirement,responsibilities.1,skills_required,matched_score
0,NaN,Big data analytics working and database wareho...,"['Big Data', 'Hadoop', 'Hive', 'Python', 'Mapr...",['The Amity School of Engineering & Technology...,['B.Tech'],['2019'],['N/A'],[None],['Electronics'],['Coca-COla'],...,NaN,NaN,NaN,Senior Software Engineer,B.Sc in Computer Science & Engineering from a ...,At least 1 year,NaN,Technical Support\nTroubleshooting\nCollaborat...,NaN,0.850000
1,NaN,Fresher looking to join as a data analyst and ...,"['Data Analysis', 'Data Analytics', 'Business ...","['Delhi University - Hansraj College', 'Delhi ...","['B.Sc (Maths)', 'M.Sc (Science) (Statistics)']","['2015', '2018']","['N/A', 'N/A']","['N/A', 'N/A']","['Mathematics', 'Statistics']",['BIB Consultancy'],...,NaN,NaN,NaN,Machine Learning (ML) Engineer,M.Sc in Computer Science & Engineering or in a...,At least 5 year(s),NaN,Machine Learning Leadership\nCross-Functional ...,NaN,0.750000
2,NaN,NaN,"['Software Development', 'Machine Learning', '...","['Birla Institute of Technology (BIT), Ranchi']",['B.Tech'],['2018'],['N/A'],['N/A'],['Electronics/Telecommunication'],['Axis Bank Limited'],...,NaN,NaN,NaN,"Executive/ Senior Executive- Trade Marketing, ...",Master of Business Administration (MBA),At least 3 years,NaN,"Trade Marketing Executive\nBrand Visibility, S...",Brand Promotion\nCampaign Management\nField Su...,0.416667
3,NaN,To obtain a position in a fast-paced business ...,"['accounts payables', 'accounts receivables', ...","['Martinez Adult Education, Business Training ...",['Computer Applications Specialist Certificate...,['2008'],[None],[None],['Computer Applications'],"['Company Name ï¼ City , State', 'Company Name...",...,NaN,NaN,NaN,Business Development Executive,Bachelor/Honors,1 to 3 years,Age 22 to 30 years,Apparel Sourcing\nQuality Garment Sourcing\nRe...,Fast typing skill\nIELTSInternet browsing & on...,0.760000
4,NaN,Professional accountant with an outstanding wo...,"['Analytical reasoning', 'Compliance testing k...",['Kent State University'],['Bachelor of Business Administration'],[None],['3.84'],[None],['Accounting'],"['Company Name', 'Company Name', 'Company Name...",...,[None],[None],"['February 15, 2021']",Senior iOS Engineer,Bachelor of Science (BSc) in Computer Science,At least 4 years,NaN,iOS Lifecycle\nRequirement Analysis\nNative Fr...,iOS\niOS App Developer\niOS Application Develo...,0.650000

In [11]:
# Keep only the columns needed for Scout AI
skills_df = skills_df[[
    "job_title",
    "job_description",
    "job_skill_set",
    "category"
]].copy()

# Check the cleaned dataset
print("Shape:", skills_df.shape)
print("\nColumns:")
print(skills_df.columns.tolist())

display(skills_df.head())

Shape: (1167, 4)

Columns:
['job_title', 'job_description', 'job_skill_set', 'category']

,job_title,job_description,job_skill_set,category
0,Sr Human Resource Generalist,SUMMARY\nTHE SR. HR GENERALIST PROVIDES HR EXP...,"['employee relations', 'talent acquisition', '...",HR
1,Human Resources Manager,BE PART OF A STELLAR TEAM AT YSB AS THE MANAGE...,"['Talent Acquisition', 'Employee Performance M...",HR
2,Director of Human Resources,OUR CLIENT IS A THRIVING ORGANIZATION OFFERING...,"['Human Resources Management', 'Recruitment', ...",HR
3,Chief Human Resources Officer,JOB TITLE: CHIEF HUMAN RESOURCES OFFICER (CHRO...,"['talent management', 'organizational developm...",HR
4,Human Resources Generalist (Hybrid Role),DESCRIPTION\n\n WHO WE ARE \n\nAVI-SPL IS A DI...,"['Microsoft Office', 'Data analysis', 'Employe...",HR

In [12]:
# Keep only useful columns
jobs_df = jobs_df[[
    "Job Title",
    "Job Description"
]].copy()

# Rename columns for consistency
jobs_df = jobs_df.rename(columns={
    "Job Title": "job_title",
    "Job Description": "job_description"
})

# Check the cleaned dataset
print("Shape:", jobs_df.shape)
print("\nColumns:")
print(jobs_df.columns.tolist())

display(jobs_df.head())

Shape: (2277, 2)

Columns:
['job_title', 'job_description']

              job_title                                    job_description
0     Flutter Developer  We are looking for hire experts flutter develo...
1      Django Developer  PYTHON/DJANGO (Developer/Lead) - Job Code(PDJ ...
2      Machine Learning  Data Scientist (Contractor)\n\nBangalore, IN\n...
3         iOS Developer  JOB DESCRIPTION:\n\nStrong framework outside o...
4  Full Stack Developer  job responsibility full stack engineer – react...

In [13]:
interview_df = pd.read_csv(
    "/kaggle/input/datasets/syedmharis/software-engineering-interview-questions-dataset/Software Questions.csv",
    encoding="latin1"
)

In [14]:
print(resume_df.columns.tolist())

['address', 'career_objective', 'skills', 'educational_institution_name', 'degree_names', 'passing_years', 'educational_results', 'result_types', 'major_field_of_studies', 'professional_company_names', 'company_urls', 'start_dates', 'end_dates', 'related_skils_in_job', 'positions', 'locations', 'responsibilities', 'extra_curricular_activity_types', 'extra_curricular_organization_names', 'extra_curricular_organization_links', 'role_positions', 'languages', 'proficiency_levels', 'certification_providers', 'certification_skills', 'online_links', 'issue_dates', 'expiry_dates', '\ufeffjob_position_name', 'educationaL_requirements', 'experiencere_requirement', 'age_requirement', 'responsibilities.1', 'skills_required', 'matched_score']

In [15]:
# Remove hidden spaces and BOM characters from all column names
resume_df.columns = (
    resume_df.columns
    .str.replace("\ufeff", "", regex=False)
    .str.strip()
)

print(resume_df.columns.tolist())

['address', 'career_objective', 'skills', 'educational_institution_name', 'degree_names', 'passing_years', 'educational_results', 'result_types', 'major_field_of_studies', 'professional_company_names', 'company_urls', 'start_dates', 'end_dates', 'related_skils_in_job', 'positions', 'locations', 'responsibilities', 'extra_curricular_activity_types', 'extra_curricular_organization_names', 'extra_curricular_organization_links', 'role_positions', 'languages', 'proficiency_levels', 'certification_providers', 'certification_skills', 'online_links', 'issue_dates', 'expiry_dates', 'job_position_name', 'educationaL_requirements', 'experiencere_requirement', 'age_requirement', 'responsibilities.1', 'skills_required', 'matched_score']

In [16]:
# Fill missing values
resume_df = resume_df.fillna("")

# Create a single text representation of each resume
resume_df["resume_text"] = (
    resume_df["career_objective"].astype(str) + " " +
    resume_df["skills"].astype(str) + " " +
    resume_df["responsibilities"].astype(str) + " " +
    resume_df["job_position_name"].astype(str)
)

# Preview
display(resume_df[["resume_text"]].head())

                                         resume_text
0  Big data analytics working and database wareho...
1  Fresher looking to join as a data analyst and ...
2   ['Software Development', 'Machine Learning', ...
3  To obtain a position in a fast-paced business ...
4  Professional accountant with an outstanding wo...

In [17]:
# Fill missing values
skills_df = skills_df.fillna("")

# Convert the skill list to string (for safety)
skills_df["job_skill_set"] = skills_df["job_skill_set"].astype(str)

# Create a single text representation of each job
skills_df["job_text"] = (
    skills_df["job_title"].astype(str) + " " +
    skills_df["job_description"].astype(str) + " " +
    skills_df["job_skill_set"]
)

# Preview
display(skills_df[["job_title", "job_text"]].head())

,job_title,job_text
0,Sr Human Resource Generalist,Sr Human Resource Generalist SUMMARY\nTHE SR. ...
1,Human Resources Manager,Human Resources Manager BE PART OF A STELLAR T...
2,Director of Human Resources,Director of Human Resources OUR CLIENT IS A TH...
3,Chief Human Resources Officer,Chief Human Resources Officer JOB TITLE: CHIEF...
4,Human Resources Generalist (Hybrid Role),Human Resources Generalist (Hybrid Role) DESCR...

In [18]:
!pip install -q sentence-transformers

In [19]:
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

In [20]:
model = SentenceTransformer("all-MiniLM-L6-v2")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [21]:
# Generate embeddings for the first 5 resumes
resume_embeddings = model.encode(
    resume_df["resume_text"].head(5).tolist(),
    convert_to_numpy=True,
    show_progress_bar=True
)

# Generate embeddings for the first 5 jobs
job_embeddings = model.encode(
    skills_df["job_text"].head(5).tolist(),
    convert_to_numpy=True,
    show_progress_bar=True
)

print("Resume embeddings shape:", resume_embeddings.shape)
print("Job embeddings shape:", job_embeddings.shape)

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Resume embeddings shape: (5, 384)
Job embeddings shape: (5, 384)

In [22]:
similarity_matrix = cosine_similarity(
    resume_embeddings,
    job_embeddings
)

print(similarity_matrix)

[[0.28986204 0.2542752  0.31071857 0.27061832 0.401669  ]
 [0.3613465  0.3622802  0.27232525 0.34026885 0.41530263]
 [0.21168351 0.2028377  0.21681532 0.23780818 0.2518385 ]
 [0.3390593  0.2901913  0.39662197 0.31271935 0.4108678 ]
 [0.3302828  0.35392922 0.3020066  0.28942502 0.405972  ]]

In [23]:
# Generate embeddings for all jobs
job_embeddings = model.encode(
    skills_df["job_text"].tolist(),
    convert_to_numpy=True,
    show_progress_bar=True
)

print(job_embeddings.shape)

Batches:   0%|          | 0/37 [00:00<?, ?it/s]

(1167, 384)

In [24]:
from sklearn.metrics.pairwise import cosine_similarity

def recommend_jobs(resume_text, top_k=5):
    # Convert resume into an embedding
    resume_embedding = model.encode([resume_text], convert_to_numpy=True)

    # Compare with all job embeddings
    similarities = cosine_similarity(resume_embedding, job_embeddings)[0]

    # Get indices of the top matching jobs
    top_indices = similarities.argsort()[-top_k:][::-1]

    recommendations = skills_df.iloc[top_indices][
        ["job_title", "category", "job_skill_set"]
    ].copy()

    recommendations["match_score"] = similarities[top_indices]

    return recommendations

In [25]:
recommend_jobs(
    resume_df.iloc[0]["resume_text"],
    top_k=5
)

,job_title,category,job_skill_set,match_score
897,Lead Software Engineer - Finance (Hybrid),FINANCE,"['Problem Solving', 'Communication', 'Teamwork...",0.661723
757,Staff Data Engineer - People & Finance Tech (R...,FINANCE,"['Leadership', 'Collaboration', 'Problem Solvi...",0.660579
244,Director of Information Technology,INFORMATION-TECHNOLOGY,"['Business Acumen', 'Collaboration', 'Problem ...",0.650347
219,"Data Engineer - Enterprise Data and Analytics,...",HR,"['Data Security', 'Data Management', 'Data Ana...",0.650064
293,Information Technology Specialist,INFORMATION-TECHNOLOGY,"['help desk support', 'customer service', 'net...",0.638848

In [26]:
import ast

skills_df["job_skill_set"] = skills_df["job_skill_set"].apply(ast.literal_eval)

skills_df["job_skill_set"].head()

0    [employee relations, talent acquisition, perfo...
1    [Talent Acquisition, Employee Performance Mana...
2    [Human Resources Management, Recruitment, Empl...
3    [talent management, organizational development...
4    [Microsoft Office, Data analysis, Employee onb...
Name: job_skill_set, dtype: object

In [27]:
import ast

def extract_resume_skills(skill_text):
    if pd.isna(skill_text) or skill_text == "":
        return []

    try:
        return [skill.lower().strip() for skill in ast.literal_eval(skill_text)]
    except:
        return []

# Test on the first resume
resume_skills = extract_resume_skills(resume_df.iloc[0]["skills"])

print(resume_skills)

['big data', 'hadoop', 'hive', 'python', 'mapreduce', 'spark', 'java', 'machine learning', 'cloud', 'hdfs', 'yarn', 'core java', 'data science', 'c++', 'data structures', 'dbms', 'rdbms', 'informatica', 'talend', 'amazon redshift', 'microsoft azure']

In [28]:
# Resume skills
resume_skills = set(extract_resume_skills(resume_df.iloc[0]["skills"]))

# Recommended job skills
job_skills = {
    skill.lower().strip()
    for skill in skills_df.iloc[897]["job_skill_set"]
}

print("Resume Skills:", len(resume_skills))
print("Job Skills:", len(job_skills))

Resume Skills: 21
Job Skills: 18

In [29]:
matched_skills = resume_skills.intersection(job_skills)
missing_skills = job_skills.difference(resume_skills)

print("=" * 60)
print("Matched Skills")
print("=" * 60)
print(sorted(matched_skills))

print("\n")

print("=" * 60)
print("Missing Skills")
print("=" * 60)
print(sorted(missing_skills))

============================================================
Matched Skills
============================================================
['hadoop', 'java', 'machine learning', 'python', 'spark']


============================================================
Missing Skills
============================================================
['aws', 'change management', 'cloud computing', 'communication', 'data modeling', 'influencing', 'itil', 'operational excellence', 'problem solving', 'relationship management', 'service management', 'sql', 'teamwork']

In [31]:
from sklearn.metrics.pairwise import cosine_similarity

def recommend_jobs_with_skill_gap(resume_index, top_k=5):
    # Get resume text
    resume_text = resume_df.iloc[resume_index]["resume_text"]

    # Generate embedding
    resume_embedding = model.encode([resume_text], convert_to_numpy=True)

    # Compare with all jobs
    similarities = cosine_similarity(resume_embedding, job_embeddings)[0]

    # Get Top-K jobs
    top_indices = similarities.argsort()[-top_k:][::-1]

    # Resume skills
    resume_skills = set(
        extract_resume_skills(
            resume_df.iloc[resume_index]["skills"]
        )
    )

    recommendations = []

    for idx in top_indices:

        job_skills = {
            skill.lower().strip()
            for skill in skills_df.iloc[idx]["job_skill_set"]
        }

        matched = sorted(resume_skills & job_skills)
        missing = sorted(job_skills - resume_skills)

        recommendations.append({
            "job_title": skills_df.iloc[idx]["job_title"],
            "category": skills_df.iloc[idx]["category"],
            "match_score": round(float(similarities[idx]), 4),
            "matched_skills": matched,
            "missing_skills": missing
        })

    return recommendations

In [32]:
results = recommend_jobs_with_skill_gap(0)

for job in results:
    print("=" * 80)
    print("Job:", job["job_title"])
    print("Category:", job["category"])
    print("Match Score:", job["match_score"])

    print("\nMatched Skills:")
    print(job["matched_skills"])

    print("\nMissing Skills:")
    print(job["missing_skills"])

================================================================================
Job: Lead Software Engineer - Finance (Hybrid)
Category: FINANCE
Match Score: 0.6617

Matched Skills:
['hadoop', 'java', 'machine learning', 'python', 'spark']

Missing Skills:
['aws', 'change management', 'cloud computing', 'communication', 'data modeling', 'influencing', 'itil', 'operational excellence', 'problem solving', 'relationship management', 'service management', 'sql', 'teamwork']
================================================================================
Job: Staff Data Engineer - People & Finance Tech (Remote)
Category: FINANCE
Match Score: 0.6606

Matched Skills:
['big data', 'hive', 'java', 'python', 'spark']

Missing Skills:
['adaptability', 'azure', 'c#', 'ci/cd', 'collaboration', 'communication', 'continuous improvement', 'docker', 'dynatrace', 'elt', 'etl', 'gatling', 'git', 'grafana', 'graphdb', 'graphql', 'kafka', 'kubernetes', 'leadership', 'mentoring', 'microstrategy', 'nosql', 'postgres', 'powerbi', 'powershell', 'problem solving', 'psychological safety', 'qlik', 'rest', 'scala', 'spring boot', 'sql']
================================================================================
Job: Director of Information Technology
Category: INFORMATION-TECHNOLOGY
Match Score: 0.6503

Matched Skills:
[]

Missing Skills:
['api development', 'business acumen', 'cloudsuite', 'collaboration', 'communication', 'hardware purchasing', 'integration experience', 'it management', 'leadership', 'problem solving', 'risk analysis', 'risk mitigation', 'software purchasing', 'strategic thinking', 'subscription management', 'warehouse management systems']
================================================================================
Job: Data Engineer - Enterprise Data and Analytics, Human Resources Stream
Category: HR
Match Score: 0.6501

Matched Skills:
['python']

Missing Skills:
['adaptability', 'cloud technologies', 'collaboration', 'communication', 'customer focus', 'data analysis', 'data management', 'data security', 'data visualization', 'data warehousing', 'etl', 'innovation', 'problem solving', 'sql', 'test automation']
================================================================================
Job: Information Technology Specialist
Category: INFORMATION-TECHNOLOGY
Match Score: 0.6388

Matched Skills:
['data science', 'java', 'machine learning', 'python']

Missing Skills:
['adaptability', 'ai tools', 'compliance knowledge', 'confidentiality', 'cultural sensitivity', 'customer service', 'dns administration', 'ellucian banner', 'help desk support', 'linux system administration', 'multi-tasking', 'networking principles', 'oracle database', 'oral communication', 'organizational skills', 'perl', 'powerbi', 'programming languages', 'r', 'salesforce', 'server administration', 'software development', 'ssl certificate maintenance', 'systems engineering software tools', 'teamwork', 'written communication']

In [33]:
print(interview_df.shape)

print(interview_df.columns.tolist())

display(interview_df.head())

(200, 5)
['Question Number', 'Question', 'Answer', 'Category', 'Difficulty']

,Question Number,Question,Answer,Category,Difficulty
0,1,What is the difference between compilation and...,Compilation translates source code into machin...,General Programming,Medium
1,2,Explain the concept of polymorphism.,Polymorphism allows objects of different class...,General Programming,Medium
2,3,Define encapsulation and give an example.,Encapsulation bundles data and methods in a cl...,General Programming,Hard
3,4,"What is an abstract class, and how is it diffe...",An abstract class can't be instantiated and ca...,General Programming,Medium
4,5,Describe the principles of Object-Oriented Pro...,"OOP principles include encapsulation, inherita...",General Programming,Medium

In [34]:
# Keep only useful columns
interview_df = interview_df[[
    "Question",
    "Answer",
    "Category",
    "Difficulty"
]].copy()

print(interview_df.head())

                                            Question  \
0  What is the difference between compilation and...
1               Explain the concept of polymorphism.
2          Define encapsulation and give an example.
3  What is an abstract class, and how is it diffe...
4  Describe the principles of Object-Oriented Pro...

                                              Answer             Category  \
0  Compilation translates source code into machin...  General Programming
1  Polymorphism allows objects of different class...  General Programming
2  Encapsulation bundles data and methods in a cl...  General Programming
3  An abstract class can't be instantiated and ca...  General Programming
4  OOP principles include encapsulation, inherita...  General Programming

  Difficulty
0     Medium
1     Medium
2       Hard
3     Medium
4     Medium

In [36]:
def recommend_interview_questions(category=None, difficulty=None, top_k=5):

    df = interview_df.copy()

    if category:
        df = df[df["Category"].str.lower() == category.lower()]

    if difficulty:
        df = df[df["Difficulty"].str.lower() == difficulty.lower()]

    return df.head(top_k)

In [37]:
recommend_interview_questions(
    category="General Programming",
    top_k=5
)

,Question,Answer,Category,Difficulty
0,What is the difference between compilation and...,Compilation translates source code into machin...,General Programming,Medium
1,Explain the concept of polymorphism.,Polymorphism allows objects of different class...,General Programming,Medium
2,Define encapsulation and give an example.,Encapsulation bundles data and methods in a cl...,General Programming,Hard
3,"What is an abstract class, and how is it diffe...",An abstract class can't be instantiated and ca...,General Programming,Medium
4,Describe the principles of Object-Oriented Pro...,"OOP principles include encapsulation, inherita...",General Programming,Medium

In [41]:
def scout_ai(resume_index, top_k=5):
    # Get recommendations
    job_results = recommend_jobs_with_skill_gap(resume_index, top_k)

    print("=" * 100)
    print("SCOUT AI CAREER REPORT")
    print("=" * 100)

    for i, job in enumerate(job_results, start=1):

        print(f"\n🏆 Recommendation #{i}")
        print("-" * 100)

        print("Job Title :", job["job_title"])
        print("Category  :", job["category"])
        print("Match     :", f"{job['match_score']:.2%}")

        print("\n✅ Matching Skills")
        if job["matched_skills"]:
            print(", ".join(job["matched_skills"]))
        else:
            print("None")

        print("\n❌ Missing Skills")
        if job["missing_skills"]:
            print(", ".join(job["missing_skills"]))
        else:
            print("None")

    print("\n" + "=" * 100)
    print("Recommended Interview Questions")
    print("=" * 100)

    questions = recommend_interview_questions(top_k=5)

    for i, row in questions.iterrows():
        print(f"\nQ{i+1}: {row['Question']}")
        print(f"Difficulty: {row['Difficulty']}")
        print(f"Category: {row['Category']}")

In [42]:
scout_ai(0)

====================================================================================================
SCOUT AI CAREER REPORT
====================================================================================================

🏆 Recommendation #1
----------------------------------------------------------------------------------------------------
Job Title : Lead Software Engineer - Finance (Hybrid)
Category  : FINANCE
Match     : 66.17%

✅ Matching Skills
hadoop, java, machine learning, python, spark

❌ Missing Skills
aws, change management, cloud computing, communication, data modeling, influencing, itil, operational excellence, problem solving, relationship management, service management, sql, teamwork

🏆 Recommendation #2
----------------------------------------------------------------------------------------------------
Job Title : Staff Data Engineer - People & Finance Tech (Remote)
Category  : FINANCE
Match     : 66.06%

✅ Matching Skills
big data, hive, java, python, spark

❌ Missing Skills
adaptability, azure, c#, ci/cd, collaboration, communication, continuous improvement, docker, dynatrace, elt, etl, gatling, git, grafana, graphdb, graphql, kafka, kubernetes, leadership, mentoring, microstrategy, nosql, postgres, powerbi, powershell, problem solving, psychological safety, qlik, rest, scala, spring boot, sql

🏆 Recommendation #3
----------------------------------------------------------------------------------------------------
Job Title : Director of Information Technology
Category  : INFORMATION-TECHNOLOGY
Match     : 65.03%

✅ Matching Skills
None

❌ Missing Skills
api development, business acumen, cloudsuite, collaboration, communication, hardware purchasing, integration experience, it management, leadership, problem solving, risk analysis, risk mitigation, software purchasing, strategic thinking, subscription management, warehouse management systems

🏆 Recommendation #4
----------------------------------------------------------------------------------------------------
Job Title : Data Engineer - Enterprise Data and Analytics, Human Resources Stream
Category  : HR
Match     : 65.01%

✅ Matching Skills
python

❌ Missing Skills
adaptability, cloud technologies, collaboration, communication, customer focus, data analysis, data management, data security, data visualization, data warehousing, etl, innovation, problem solving, sql, test automation

🏆 Recommendation #5
----------------------------------------------------------------------------------------------------
Job Title : Information Technology Specialist
Category  : INFORMATION-TECHNOLOGY
Match     : 63.88%

✅ Matching Skills
data science, java, machine learning, python

❌ Missing Skills
adaptability, ai tools, compliance knowledge, confidentiality, cultural sensitivity, customer service, dns administration, ellucian banner, help desk support, linux system administration, multi-tasking, networking principles, oracle database, oral communication, organizational skills, perl, powerbi, programming languages, r, salesforce, server administration, software development, ssl certificate maintenance, systems engineering software tools, teamwork, written communication

====================================================================================================
Recommended Interview Questions
====================================================================================================

Q1: What is the difference between compilation and interpretation?
Difficulty: Medium
Category: General Programming

Q2: Explain the concept of polymorphism.
Difficulty: Medium
Category: General Programming

Q3: Define encapsulation and give an example.
Difficulty: Hard
Category: General Programming

Q4: What is an abstract class, and how is it different from an interface?
Difficulty: Medium
Category: General Programming

Q5: Describe the principles of Object-Oriented Programming (OOP).
Difficulty: Medium
Category: General Programming